<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>8f17ee8f-555b-4799-9f0f-27f1b81eea2c</UserSecretsId>
  </PropertyGroup>

</Project>
