<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>XYZ.Billing.API.Features</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Carter" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\XYZ-Billing.API.PaymentGateways\XYZ-Billing.API.PaymentGateways.csproj" />
	</ItemGroup>
</Project>
